# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: 💡 我有个想法
description: 建议新功能或改进现有功能
title: "[建议] "
labels: ["enhancement"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        ### 💝 温馨提醒

        感谢你的创意想法！如果这个项目对你有帮助，欢迎给项目点个 ⭐ **Star**！

        好的建议让项目变得更加实用。**欢迎用截图或示例**来展示你的想法！

  - type: dropdown
    id: feature-category
    attributes:
      label: 🏷️ 建议类别
      options:
        - 数据源相关（新增平台、改进抓取等）
        - 分析功能相关（算法改进、筛选优化等）
        - 通知方式相关（新增通知渠道、消息格式等）
        - 配置管理相关（设置优化、界面改进等）
        - 部署运维相关（安装简化、监控告警等）
        - 数据展示相关（报告格式、图表可视化等）
        - 性能优化相关
        - 用户体验改进
        - 其他想法
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 💭 详细描述你的想法
      description: 请详细描述你希望添加的功能
      placeholder: |
        请详细描述：
        - 你希望增加什么功能
        - 这个功能应该怎么使用
        - 使用后能达到什么效果

        💡 提示：如果有类似功能的截图作为参考就更好了！
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 🎯 什么时候会用到这个功能
      description: 这个功能在什么场景下使用？
      placeholder: |
        例如：
        - 当我需要...的时候
        - 在...情况下会很方便
        - 可以解决...问题
        - 能够帮助...用户
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 🛠️ 实现想法（可选）
      description: 如果你有实现思路，欢迎分享
      placeholder: |
        - 功能界面应该怎么设计
        - 配置应该怎么设置
        - 参考哪些类似的工具或网站
        - 其他实现建议

  - type: textarea
    id: mockups-examples
    attributes:
      label: 📷 功能示意图（推荐）
      description: 上传功能示意图、参考截图或手绘草图
      placeholder: |
        请上传：
        - 功能界面的设计图（手绘也可以）
        - 类似功能的参考截图
        - 使用流程的示意图

        💡 可视化的说明最容易理解！

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 其他补充说明
      description: 其他想要补充的内容
      placeholder: |
        - 相关的参考资料链接
        - 类似功能的其他工具
        - 更多使用场景说明
        - 其他相关想法
