# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: ⚙️ 设置遇到困难
description: 配置相关的问题或需要帮助
title: "[设置] "
labels: ["配置", "帮助"]
assignees:
  - sansan0
body:
  - type: markdown
    attributes:
      value: |
        ### 💝 温馨提醒

        如果这个项目对你有帮助，欢迎给项目点个 ⭐ **Star**！

        遇到设置问题不要担心，**强烈建议上传配置文件和错误信息的截图**。

        📖 **建议先查看项目说明文档**，很多常见问题都有详细说明。

  - type: dropdown
    id: config-type
    attributes:
      label: 🏷️ 配置问题类别
      options:
        - 基础配置问题（config.yaml 设置）
        - 通知配置问题（webhook、消息推送等）
        - 部署配置问题（Docker、GitHub Actions等）
        - 关键词配置问题（frequency_words.txt 设置）
        - 环境配置问题（Python、依赖包等）
        - 其他配置问题
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 🖥️ 使用环境
      options:
        - 本地运行（直接在电脑上运行）
        - Docker 容器运行
        - GitHub Actions 自动运行
        - 其他方式
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 📝 详细描述问题
      description: 请详细描述你遇到的设置问题
      placeholder: |
        请详细描述：
        - 遇到的具体问题是什么
        - 你希望达到什么效果
        - 已经尝试了哪些方法
        - 参考了哪些文档或教程

        💡 问题截图能提供更多信息！
    validations:
      required: true

  - type: textarea
    id: config-content
    attributes:
      label: 📄 配置内容
      description: 请提供相关的配置内容（记得隐藏敏感信息如 webhook 地址）
      placeholder: |
        请贴出相关的配置内容（记得隐藏 webhook 地址等敏感信息）：

        ```yaml
        notification:
          enable_notification: true
          webhooks:
            feishu_url: "***隐藏***"
            dingtalk_url: "***隐藏***"
        ```

        💡 配置文件截图也很有用！
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: ❌ 错误信息（如果有的话）
      description: 如果程序显示了错误信息，请贴出来
      placeholder: |
        如果有错误信息，请完整复制到这里：

        ```
        错误信息内容...
        ```

        💡 错误信息的截图也很重要！

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 相关截图（强烈推荐）
      description: 上传配置界面、错误信息等截图
      placeholder: |
        请上传相关截图，特别是：
        - 配置文件内容截图
        - 错误信息截图
        - 操作界面截图
        - 期望效果的参考图

        💡 截图是最直观的问题展示方式！

  - type: textarea
    id: additional-info
    attributes:
      label: 📎 其他补充信息
      description: 其他可能有用的信息
      placeholder: |
        - 操作系统版本（如 Windows 11、macOS）
        - Python 版本信息
        - 网络环境特殊情况
        - 具体使用场景说明
        - 其他你觉得相关的信息
